[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "slampy"
version = "1.0.0"
description = ""
authors = ["Your Name <your.email@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
numpy = "1.26.3"
jax = "0.4.23"
jaxlib = { version = "0.4.23", extras = ["cuda12", "cudnn89"] }
opencv-contrib-python = "4.9.0.80"
open3d = "0.18.0"

[tool.poetry.dev-dependencies]
# Add development dependencies here